### ISSUE TITLE
help

### ISSUE THREAD

**Issue by s0daa** [Ciremun/freedom#104]
is this a cheat or a trainer

**Comment by Ciremun** [comment]
what are you asking specifically? in my experience cheats and trainers kinda mean the same thing?
freedom is an internal cheat for osu! (std) with blatant and non-blatant 'game-breaking' features.

**Comment by Ciremun** [comment]
'Game trainers are programs made to modify memory of a computer game thereby modifying its behavior using addresses and values, in order to allow cheating' (from Google)
so same thing basically
