### ISSUE TITLE
Не происходит инжект.

### ISSUE THREAD

**Issue by FO1ZZY** [Ciremun/freedom#110]
После запуска .exe, консоль появляется на секунду и пропадает,сам длл инжектится, но меню софта не появляется

**Comment by Ciremun** [comment]
Скорее всего режим совместимости в осу включен. Пока не поддерживается.

**Comment by FO1ZZY** [comment]
Не подскажешь как выключить?

**Comment by Ciremun** [comment]
в настройках игры, compatibility mode

**Comment by FO1ZZY** [comment]
а все. Спасибо
