### ISSUE TITLE
!!! REPLAY BOT BROKE !!!

### ISSUE THREAD

**Issue by PremiumCheatsYeety** [Ciremun/freedom#124]
replaybot is fucked up, goes completely wrong for first 20 seconds or so

**Comment by Ciremun** [comment]
@PremiumCheatsYeety  still works for me, can i have a replay / beatmap so i can check?
other issues could be: no fullscreen, raw input game setting, in-game sensitivity is not 1x, or using a tablet
if replay misses hard, aimbot or relax should miss too, it uses the same method for passing keystrokes

**Comment by PremiumCheatsYeety** [comment]
restarting computer fixed it, interesting
