### ISSUE TITLE
a lot of stutters/microfreezes.

### ISSUE THREAD

**Issue by jg7df7xr7** [Ciremun/freedom#144]
all works, but when i play a map im getting random stutters/freezes, idk why i tested old versions same issue, all game settings same issue... can somebody help me?
![B520jJ8 (1)](https://github.com/Ciremun/freedom/assets/163752697/edc6ef14-37ab-45aa-817f-0dcf1ae54849)

**Comment by Ciremun** [comment]
some feature causing it? or injection itself
is it the latest release or latest commit from actions?

**Comment by ShinoharaYuu** [comment]
> some feature causing it? or injection itself is it the latest release or latest commit from actions?

i have the same issue, tried both latest release and commit from action, for me it increase latency after injecting, and start freezing after unmoding either HD or FL

**Comment by BlossomandMilk** [comment]
Same issue with every version here, the new osu update breaks everything :/

**Comment by jg7df7xr7** [comment]
> some feature causing it? or injection itself is it the latest release or latest commit from actions?

i had everything off instead of relax i think its because of the injection
latest release

**Comment by Ciremun** [comment]
this works for me so far:
rename freedom.dll to something else and inject (in cmd.exe):
```
freedom_injector.exe osu!.exe renamed.dll
```
or use a manual map injection method (like [ExtremeInjector](https://github.com/master131/ExtremeInjector))
i guess i will just add manual map later

**Comment by BlossomandMilk** [comment]
can you fix this in the next build/version?

**Comment by Ciremun** [comment]
> can you fix this in the next build/version?

i will add a manual map injector, does renaming the dll work for you?

**Comment by BlossomandMilk** [comment]
yeah it works with the injector what you linked

**Comment by jg7df7xr7** [comment]
> this works for me so far: rename freedom.dll to something else and inject (in cmd.exe):
> 
> ```
> freedom_injector.exe osu!.exe renamed.dll
> ```
> 
> or use a manual map injection method (like [ExtremeInjector](https://github.com/master131/ExtremeInjector)) i guess i will just add manual map later

works now ty.
