### ISSUE TITLE
manual map injector

### ISSUE THREAD

**Issue by Ciremun** [Ciremun/freedom#146]
https://github.com/Ciremun/freedom/issues/145
https://github.com/Ciremun/freedom/issues/144

**Comment by Vctr5-5** [comment]
There have been changes to osu!auth.dll in recent updates.
Due to this, the module freedom.dll may be detected

**Comment by Vctr5-5** [comment]
Does not freeze when playing offline, but freezes when playing online

**Comment by Ciremun** [comment]
> Does not freeze when playing offline, but freezes when playing online

which version? can't reproduce on latest release / action:  
https://github.com/Ciremun/freedom/actions/runs/8697453103/artifacts/1416287185
or  
https://github.com/Ciremun/freedom/releases/download/v0.94.1/freedom.v0.94.1.zip
