### ISSUE TITLE
микрофризы и взлеты мса (microfreezes and raising ms)

### ISSUE THREAD

**Issue by rewsedd** [Ciremun/freedom#147]
я не особо понимаю,что делать в такой ситуации (I don’t really understand what to do in this situation)
![image](https://github.com/Ciremun/freedom/assets/167029978/ea209e2c-06ca-423a-8975-f684c94534ce)

**Comment by Ciremun** [comment]
пока временный фикс https://github.com/Ciremun/freedom/issues/144#issuecomment-2053630852

**Comment by rewsedd** [comment]
спасибо!
