### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Renonya** [Ciremun/freedom#159]
The readme states that the HD remover is detect, but can timewarp be used?? I heard that timewarp is detected

**Comment by Ciremun** [comment]
seems like hd remover is not detected for now, see latest commit artifact:  
https://github.com/Ciremun/freedom/actions/runs/9038839222/artifacts/1492710828
timewarp and other features that affect replays may be detected manually, yes
timewarp doesnt update timings in current implementation, so spinners and sliders may look weird

**Comment by fantiachan** [comment]
Thank you for your reply, I understand

**Comment by Renonya** [comment]
Thank you for your reply, I understand
