### ISSUE TITLE
everything doesnt work

### ISSUE THREAD

**Issue by shimmer58** [Ciremun/freedom#57]
???

**Comment by Ciremun** [comment]
@shimmer58 at least AR, CS, OD changer is still working on my machine, the other stuff doesn't work because osu_manager_ptr broke, i'll look into that later.

**Comment by Ciremun** [comment]
@shimmer58 fixed in da6387d91f680602860ddef9992e84a68a88335b, download link -https://github.com/Ciremun/freedom/suites/9385525508/artifacts/442470857
