### ISSUE TITLE
Another problem with injection.

### ISSUE THREAD

**Issue by xVirum** [Ciremun/freedom#62]
Hi, I realize this is probably a common problem, but I have a problem with the injection. I tried to inject with freedom.exe, I also did it with Process Hacker, but still it doesn't work. The funny thing is that I can't unload the cheat because it can't find the right module, although when I reload in the module list, freedom.dll is still there. Perhaps I explained something incorrectly, so here is a link to a video with the problem. 
https://www.youtube.com/watch?v=aMYeayl6HmE

**Comment by Ciremun** [comment]
hi, i could help in discord Ciremun#8516
i don't really know what causes this behaviour. also direct unload would crash the game anyway because of the hook

**Comment by xVirum** [comment]
I sent a request
