### ISSUE TITLE
Relax & Aimbot are red on new update

### ISSUE THREAD

**Issue by GamebP** [Ciremun/freedom#83]
![image](https://user-images.githubusercontent.com/88152063/227797010-8679b14d-c56b-4a6c-a0cc-5970b166120d.png)
Tottaly red. It did not search memorys for them.. just skipped.

**Comment by GamebP** [comment]
Pattern scanner cant find beacuse the original one is wrong.

**Comment by Ciremun** [comment]
hopefully fixed, posting a release as soon as it builds on CI

**Comment by Ciremun** [comment]
give it a try https://github.com/Ciremun/freedom/releases/download/v0.88/freedom.v0.88.zip

**Comment by GamebP** [comment]
Works as prefect. I have you messaged on discord 
Me the user: SkyDash
