### ISSUE TITLE
Idea's to work on. If it's even possoble..

### ISSUE THREAD

**Issue by GamebP** [Ciremun/freedom#84]
1. Follow the slider not teleport
2. Cursordance? ([I don't know ](https://github.com/TheCodingNina/Osu-Bot/blob/master/Osu!Bot%20V2/CursorMovement.h)) Maybe dance from off screen to in screen..
3. When i move the mouse At the breakpoint then that aimbot stops moving a little bit. Gives me 100 or miss.
4. Problobly searchable memory scans in future.
5. Play fast (like fast timewarp and just plays fast)
6. Make the max range to spin more then 477

**Comment by GamebP** [comment]
What do you think Ciremun?

**Comment by dafijo** [comment]
This is up to ciremun to make it i depends on motivation to continue making these, also are these undetected and ready to be used in osu?

**Comment by Ciremun** [comment]
probably detected
