### ISSUE TITLE
+ vcvarsall x86 + ~~~~~~~~~     + CategoryInfo          : ObjectNotFound: (vcvarsall:String) [], CommandNotFoundException     + FullyQualifiedErrorId : CommandNotFoundException

### ISSUE THREAD

**Issue by Kurokoteii** [Ciremun/freedom#93]
![2](https://github.com/Ciremun/freedom/assets/132693325/5aaed3ae-e607-47ec-a917-f210954aab83)
![1](https://github.com/Ciremun/freedom/assets/132693325/55ecff08-7e32-4464-b602-cb0a3f5948ef)

I've been trying to build the latest commits, but the commands are not found by VS, I personally never use cmdline compiling. I have all the necessary build tools installed by the way. I'm looking forward for your help.

**Comment by Ciremun** [comment]
cl.exe, csc.exe and link.exe are not in PATH by default, that's why we need vcvarsall, x86 is for 32-bit executables
the default path with VS2022 IDE (not just build tools) is:
```
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x86
```
^ you should be able to paste and run that line from cmd.exe
or add this line to windows path to access vcvarsall at any time directly (like in the readme)
```
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build
```

**Comment by Kurokoteii** [comment]
> cl.exe, csc.exe and link.exe are not in PATH by default, that's why we need vcvarsall, x86 is for 32-bit executables the default path with VS2022 IDE (not just build tools) is:
> 
> ```
> "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x86
> ```
> 
> ^ you should be able to paste and run that line from cmd.exe or add this line to windows path to access vcvarsall at any time directly (like in the readme)
> 
> ```
> C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build
> ```

Thank you a lot! I'll search for a fix for the sliders now. If I ever fix it I'll open a pull request!

**Comment by Ciremun** [comment]
sliders fixed (or at least another good approach was introduced)
